apiVersion: v1
kind: Service
metadata:
    name: "mslearn111121-524d"
    labels:
        app: "mslearn111121-524d"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "mslearn111121-524d"