on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: fahaddemo.azurecr.io
        username: ${{ secrets.acr_fahaddemo_username }}
        password: ${{ secrets.acr_fahaddemo_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t fahaddemo.azurecr.io/mslearn111121:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push fahaddemo.azurecr.io/mslearn111121:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_mslearn111121_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep mslearn111121bc09 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace mslearn111121bc09`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: mslearn111121bc09
        container-registry-url: fahaddemo.azurecr.io
        container-registry-username: ${{ secrets.acr_fahaddemo_username }}
        container-registry-password: ${{ secrets.acr_fahaddemo_password }}
        secret-name: mslearn11112dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: mslearn111121bc09
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          fahaddemo.azurecr.io/mslearn111121:${{ github.sha }}
        imagepullsecrets: |
          mslearn11112dockerauth
